# Generated by Django 3.1.5 on 2021-07-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0006_author_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_length',
            field=models.IntegerField(null=True, verbose_name='Максимальный размер'),
        ),
    ]
